version: '3.7'
networks:
  nest-network:
    external: true

services:
  my-nest-service:
    build: .
    restart: always
    ports:
      - "4000:4000"
    networks:
      - nest-network
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
